Repository BradWalsh97/SlightlyDelayedGram, pull requests merged in 2020-04, with the labels that each got.

#74 Issue#60
  SlightlyDelayedGram/db.sqlite3
  SlightlyDelayedGram/media/photos/022118_EE_horses_feat.jpg
  SlightlyDelayedGram/media/photos/104656646-Melbourne.jpg
  SlightlyDelayedGram/media/photos/104656646-Melbourne_9kqHZfl.jpg
  SlightlyDelayedGram/media/photos/1208556996-850x560.webp
  SlightlyDelayedGram/media/photos/440px-Allegheny_Monongahela_Ohio.jpg
  SlightlyDelayedGram/media/photos/440px-Allegheny_Monongahela_Ohio_qNj7qvo.jpg
  SlightlyDelayedGram/media/photos/460px-Skyscrapers_of_Shinjuku_2009_January_revised.jpg
  SlightlyDelayedGram/media/photos/460px-Skyscrapers_of_Shinjuku_2009_January_revised_8KJ2SCd.jpg
  SlightlyDelayedGram/media/photos/74876E_FRONT.jpg
  SlightlyDelayedGram/media/photos/GettyImages-1128999554.jpg
  SlightlyDelayedGram/media/photos/Nokota_Horses_cropped.jpg
  SlightlyDelayedGram/media/photos/Sheth_Motisha_Tonk_01.jpg
  SlightlyDelayedGram/media/photos/bda112e2-efd0-4464-8b24-7d6b3f0224a7-USATSI_13793959.webp
  SlightlyDelayedGram/media/photos/cut.jpg
  SlightlyDelayedGram/media/photos/eft_alpha_newvisuals_3-800x500.webp
  SlightlyDelayedGram/media/photos/escape-from-tarkov-beta-cover.jpg
  SlightlyDelayedGram/media/photos/escape-from-tarkov.png
  SlightlyDelayedGram/media/photos/escape-from-tarkov_e0awmhj.png
  SlightlyDelayedGram/media/photos/horse-2063672_1920.jpg
  SlightlyDelayedGram/media/photos/lowfive-e1574190897824-1024x683.jpg
  SlightlyDelayedGram/media/photos/maxresdefault.jpg
  SlightlyDelayedGram/media/photos/sn-expressions.jpg
  SlightlyDelayedGram/media/photos/usa_today_13746018.0.webp
  SlightlyDelayedGram/users/__pycache__/views.cpython-38.pyc
  SlightlyDelayedGram/users/templates/users/base.html
  SlightlyDelayedGram/users/templates/users/main.html
  SlightlyDelayedGram/users/templates/users/peer_profile.html
  SlightlyDelayedGram/users/templates/users/picture_detail.html
  SlightlyDelayedGram/users/views.py
Labels: bug

#76 Closes Issue#70
  .gitignore
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/__init__.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/settings.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/urls.cpython-36.pyc
  SlightlyDelayedGram/tests/tests_Comments.py
  SlightlyDelayedGram/tests/tests_postingPics.py
Labels: Sub-task

#77 Like function added
  SlightlyDelayedGram/.idea/misc.xml
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/__init__.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/settings.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/urls.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/wsgi.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/urls.py
  SlightlyDelayedGram/db.sqlite3
  SlightlyDelayedGram/users/__pycache__/__init__.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/admin.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/apps.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/forms.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/models.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/signals.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/views.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/0003_picture_likes.py
  SlightlyDelayedGram/users/migrations/__pycache__/0001_initial.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0002_auto_20200306_0029.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0003_picture_likes.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/__init__.cpython-38.pyc
  SlightlyDelayedGram/users/models.py
  SlightlyDelayedGram/users/templates/users/main.html
  SlightlyDelayedGram/users/templates/users/peer_profile.html
  SlightlyDelayedGram/users/templates/users/picture_detail.html
  SlightlyDelayedGram/users/templates/users/profile.html
  SlightlyDelayedGram/users/views.py
Labels: Sub-task

#82 Fixed following and added unfollowing
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/__init__.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/settings.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/urls.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/wsgi.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/urls.py
  SlightlyDelayedGram/tests/tests_Following.py
  SlightlyDelayedGram/tests/tests_Views.py
  SlightlyDelayedGram/users/__pycache__/__init__.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/admin.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/apps.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/forms.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/models.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/signals.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/views.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/0004_auto_20200407_1603.py
  SlightlyDelayedGram/users/migrations/__pycache__/0001_initial.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0002_auto_20200306_0029.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0003_picture_likes.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0004_auto_20200407_1603.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/__init__.cpython-38.pyc
  SlightlyDelayedGram/users/models.py
  SlightlyDelayedGram/users/templates/users/peer_profile.html
  SlightlyDelayedGram/users/tests.py
  SlightlyDelayedGram/users/views.py
Labels: Sub-task

#89 Updated README
  README.md
Labels: documentation

#92 Closes #73
  SlightlyDelayedGram/tests/tests_TrendingPage.py
Labels: Sub-task

#93 Merge Sprint4 into master
  README.md
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/urls.cpython-38.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/urls.py
  SlightlyDelayedGram/db.sqlite3
  SlightlyDelayedGram/media/photos/usa_today_13746018.0_DQMNvMp.webp
  SlightlyDelayedGram/media/profile_pics/12122468_10153652549461182_5098078448975274669_n.jpg
  SlightlyDelayedGram/media/profile_pics/12122468_10153652549461182_5098078448975274669_n_FgmrBst.jpg
  SlightlyDelayedGram/media/profile_pics/12795081_1159194244099472_4290996471701452775_o.jpg
  SlightlyDelayedGram/media/profile_pics/1_heL-f8bPywxsNG2snNPIwQ.jpeg
  SlightlyDelayedGram/media/profile_pics/35671518_1896091650447326_1486583821477347328_o.jpg
  SlightlyDelayedGram/media/profile_pics/36467677_1826084077488356_5366434118772981760_o.jpg
  SlightlyDelayedGram/media/profile_pics/40359305_2182113938723045_8521560830066556928_o.jpg
  SlightlyDelayedGram/tests/tests_Following.py
  SlightlyDelayedGram/tests/tests_LikingPictures.py
  SlightlyDelayedGram/tests/tests_TrendingPage.py
  SlightlyDelayedGram/tests/tests_Views.py
  SlightlyDelayedGram/users/__pycache__/models.cpython-38.pyc
  SlightlyDelayedGram/users/__pycache__/views.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/0001_initial.py
  SlightlyDelayedGram/users/migrations/0002_auto_20200306_0029.py
  SlightlyDelayedGram/users/migrations/__pycache__/0001_initial.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0002_auto_20200304_1943.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0002_auto_20200306_0029.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0002_picture.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0003_auto_20200302_1457.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0004_comment.cpython-38.pyc
  SlightlyDelayedGram/users/migrations/__pycache__/0005_auto_20200304_1926.cpython-38.pyc
  SlightlyDelayedGram/users/models.py
  SlightlyDelayedGram/users/templates/users/base.html
  SlightlyDelayedGram/users/templates/users/login.html
  SlightlyDelayedGram/users/templates/users/logout.html
  SlightlyDelayedGram/users/templates/users/main.html
  SlightlyDelayedGram/users/templates/users/peer_profile.html
  SlightlyDelayedGram/users/templates/users/picture_detail.html
  SlightlyDelayedGram/users/templates/users/profile.html
  SlightlyDelayedGram/users/templates/users/register.html
  SlightlyDelayedGram/users/templates/users/search.html
  SlightlyDelayedGram/users/templates/users/template.html
  SlightlyDelayedGram/users/templates/users/trending.html
  SlightlyDelayedGram/users/views.py
Labels: Story
