Repository BradWalsh97/SlightlyDelayedGram, pull requests merged in 2020-03, with the labels that each got.

#38 Added "Trending" button to nav bar - Closes #31
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/__init__.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/settings.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/urls.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/wsgi.cpython-36.pyc
  SlightlyDelayedGram/db.sqlite3
  SlightlyDelayedGram/template/main.html
  SlightlyDelayedGram/users/templates/users/main.html
  SlightlyDelayedGram/users/templates/users/template.html
Labels: Sub-task

#40 Revert "Added "Trending" button to nav bar - Closes #31"
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/__init__.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/settings.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/urls.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/wsgi.cpython-36.pyc
  SlightlyDelayedGram/db.sqlite3
  SlightlyDelayedGram/template/main.html
  SlightlyDelayedGram/users/templates/users/main.html
  SlightlyDelayedGram/users/templates/users/template.html
Labels: Sub-task

#41 Added "Trending" button to nav bar - Closing #31
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/__init__.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/settings.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/urls.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/wsgi.cpython-36.pyc
  SlightlyDelayedGram/db.sqlite3
  SlightlyDelayedGram/template/main.html
  SlightlyDelayedGram/users/templates/users/main.html
  SlightlyDelayedGram/users/templates/users/template.html
Labels: Sub-task

#51 Issue #26 create comment containers for each picture
  SlightlyDelayedGram/db.sqlite3
  SlightlyDelayedGram/media/photos/00-promo-image-florence-italy-travel-guide_eFkz3bR.jpg
  SlightlyDelayedGram/media/photos/Italy-Puglia-Alberobello-Lecce-Trulli-PUS-600x600_6BAcFgk.webp
  SlightlyDelayedGram/media/photos/Region-Molise-in-center-Italy-the-little-villages-are-Limosano-and-S.Angelo-Limos_BINyP9c.jpg
  SlightlyDelayedGram/media/photos/winter-adventures-tours-in-italy-400X400__pkmF42u.jpg
  SlightlyDelayedGram/users/__pycache__/views.cpython-38.pyc
  SlightlyDelayedGram/users/templates/users/main.html
  SlightlyDelayedGram/users/templates/users/picture_detail.html
  SlightlyDelayedGram/users/templates/users/profile.html
  SlightlyDelayedGram/users/views.py
Labels: bug

#53 Add Software Diagrams to Repo- Closses #45
  Architecture Diagrams/High Level  Architecture Diagram.png
  Architecture Diagrams/Software Architecture Diagram.png
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/__init__.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/settings.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/urls.cpython-36.pyc
  SlightlyDelayedGram/SlightlyDelayedGram/__pycache__/wsgi.cpython-36.pyc
  SlightlyDelayedGram/template/main.html
  SlightlyDelayedGram/users/templates/users/template.html
Labels: documentation

#54 Issue #24
  SlightlyDelayedGram/SlightlyDelayedGram/urls.py
  SlightlyDelayedGram/db.sqlite3
  SlightlyDelayedGram/users/models.py
  SlightlyDelayedGram/users/templates/users/peer_profile.html
  SlightlyDelayedGram/users/templates/users/profile.html
  SlightlyDelayedGram/users/views.py
Labels: Sub-task

#57 Email notification when a user follows you works
  SlightlyDelayedGram/SlightlyDelayedGram/settings.py
  SlightlyDelayedGram/users/views.py
Labels: Sub-task

#58 Fixed readme
  README.md
Labels: documentation
